# TheBridge Config
# -----------------

# Lobby/Waiting Scoreboard Ip
LobbyScoreboard: play.yourservername.com
# Starting/LobbyStarting Scoreboard Ip
StartScoreboard: play.yourservername.com
# Game/In Game Scoreboard
GameScoreboard: play.yourservername.com
#Restart/Restarting Game Scoreboard
RestartScoreboard: play.yourservername.com

# ----------------
