# THEBRIDGE CONFIG
LobbyScoreboard: §eplay.yourservername.com
StartScoreboard: §eplay.yourservername.com
GameScoreboard: §eplay.yourservername.com
RestartScoreboard: §eplay.yourservername.com
# End of config
